#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────
#  MGG — one-command installer for Ubuntu (22.04 / 24.04).
#  Usage:  sudo bash deploy/install.sh
#  Optional env: APP_DOMAIN=panel.example.com  NODE_PUBLIC_IP=1.2.3.4
# ─────────────────────────────────────────────────────────────────────────
set -euo pipefail

GREEN='\033[0;32m'; CYAN='\033[0;36m'; YEL='\033[1;33m'; NC='\033[0m'
say() { echo -e "${CYAN}▸${NC} $*"; }
ok()  { echo -e "${GREEN}✓${NC} $*"; }
warn(){ echo -e "${YEL}!${NC} $*"; }

if [ "$(id -u)" -ne 0 ]; then echo "Please run as root (sudo)."; exit 1; fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

# ── 1. Docker ─────────────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  say "Installing Docker…"
  curl -fsSL https://get.docker.com | sh
  ok "Docker installed"
else
  ok "Docker present ($(docker --version))"
fi

if ! docker compose version >/dev/null 2>&1; then
  warn "Docker Compose plugin missing — installing…"
  apt-get update -y && apt-get install -y docker-compose-plugin
fi

# ── 2. Host data directories ───────────────────────────────────────────────
say "Creating data directories under /var/lib/mgg…"
mkdir -p /var/lib/mgg/volumes /var/lib/mgg/backups
ok "Data directories ready"

# ── 3. Environment ─────────────────────────────────────────────────────────
gen() { openssl rand -base64 48 | tr -d '\n/+=' | cut -c1-48; }

# Offer a domain (for automatic HTTPS) when running interactively and none was
# pre-set. Gated on a TTY so the `curl | sudo bash` path skips it silently.
if [ -z "${APP_DOMAIN:-}" ] && [ -t 0 ] && [ ! -f .env ]; then
  read -rp "$(echo -e "${CYAN}▸${NC} Domain for the panel (blank = serve on plain http://<ip>): ")" _d || true
  [ -n "${_d:-}" ] && export APP_DOMAIN="$_d"
fi

if [ ! -f .env ]; then
  say "Generating .env with fresh secrets…"
  # The node address (DEFAULT_NODE_FQDN / NODE_PUBLIC_IP) must be reachable BOTH
  # by the panel container AND by the browsers that open the live console — i.e.
  # an address that resolves on the same network as the clients. Behind a home
  # router/NAT, the public WAN IP (api.ipify.org) is usually NOT reachable from
  # inside (no hairpin NAT) and would make server provisioning fail with
  # "fetch failed". So prefer the primary LAN IP. For a box that is directly
  # internet-reachable (port-forwarded), pass NODE_PUBLIC_IP=1.2.3.4 to override.
  LAN_IP="$(ip -4 route get 1.1.1.1 2>/dev/null | sed -n 's/.* src \([0-9.]*\).*/\1/p' | head -1)"
  PUBLIC_IP="${NODE_PUBLIC_IP:-${LAN_IP:-$(curl -fsSL https://api.ipify.org 2>/dev/null || echo 127.0.0.1)}}"
  DOMAIN="${APP_DOMAIN:-:80}"
  # Caddy fronts the panel on :80 (the panel's own port 3000 isn't published).
  APP_URL="http://${PUBLIC_IP}"
  [ "$DOMAIN" != ":80" ] && APP_URL="https://${DOMAIN}"

  cat > .env <<EOF
# Generated by deploy/install.sh on $(date -u +%FT%TZ)
POSTGRES_USER=mgg
POSTGRES_PASSWORD=$(gen)
POSTGRES_DB=mgg

APP_URL=${APP_URL}
APP_DOMAIN=${DOMAIN}
AUTH_SECRET=$(gen)
API_JWT_SECRET=$(gen)
DAEMON_TOKEN=$(gen)

DEFAULT_NODE_FQDN=${DOMAIN/:80/${PUBLIC_IP}}
NODE_PUBLIC_IP=${PUBLIC_IP}
DAEMON_PORT=8080

# Bootstrap admin (optional — otherwise the first account you register is admin)
ADMIN_EMAIL=
ADMIN_PASSWORD=
ADMIN_USERNAME=admin
EOF
  ok ".env created (public IP: ${PUBLIC_IP})"
else
  ok ".env already exists — leaving it untouched"
fi

# ── 3b. Docker container DNS ────────────────────────────────────────────────
# Some hosts hand containers a resolver that only answers on the host (e.g. a
# router/systemd-resolved address), which makes image builds and `npm install`
# hang on DNS. Add a public DNS fallback if Docker isn't already configured.
if [ ! -f /etc/docker/daemon.json ]; then
  say "Configuring Docker DNS fallback (1.1.1.1 / 8.8.8.8)…"
  cat > /etc/docker/daemon.json <<'JSON'
{
  "dns": ["1.1.1.1", "8.8.8.8"]
}
JSON
  systemctl restart docker 2>/dev/null || true
  sleep 4
  ok "Docker DNS configured"
fi

# ── 4. Build & launch ──────────────────────────────────────────────────────
say "Building images (first run downloads & compiles — a few minutes)…"
docker compose build

say "Starting the stack…"
docker compose up -d

# ── 5. Optional: host firewall (DDoS mitigation) ───────────────────────────
if [ "${APPLY_FIREWALL:-0}" = "1" ]; then
  say "Applying nftables firewall (SYN-flood + UDP rate limiting)…"
  SSH_PORT="${SSH_PORT:-22}" bash "$ROOT_DIR/deploy/firewall.sh" apply || warn "firewall step failed (continuing)"
else
  warn "Host firewall NOT applied. Review deploy/firewall.sh, then run:"
  warn "    sudo SSH_PORT=22 bash deploy/firewall.sh apply"
  warn "  (opt-in to avoid locking yourself out on a non-standard SSH port)."
fi

APP_URL="$(grep ^APP_URL .env | cut -d= -f2-)"
echo
echo -e "${GREEN}┌──────────────────────────────────────────────┐${NC}"
echo -e "${GREEN}│            MGG is up and running!         │${NC}"
echo -e "${GREEN}└──────────────────────────────────────────────┘${NC}"
echo
echo -e "   Panel:   ${GREEN}${APP_URL}${NC}"
echo -e "   Daemon:  port 8080"
echo
echo -e "   ${YEL}→ The FIRST account you register becomes the admin.${NC}"
echo
echo "   Handy commands:"
echo "     make ps       # status"
echo "     make logs     # tail panel + daemon"
echo "     make down     # stop"
echo "     make update   # pull + rebuild + restart"
