import type { GameTemplate } from "./template.js";

/**
 * ICARUS — dedicated server (Steam AppID 2089300).
 * Icarus ships a Windows-only dedicated server, so on Linux it runs under
 * Wine/Proton inside a SteamCMD-based image (jammsen/docker-icarus-dedicated-server).
 * Worlds are "prospects"; the server is configured through ServerSettings.ini,
 * which we drive from these variables.
 */
export const icarus: GameTemplate = {
  id: "icarus-dedicated",
  game: "icarus",
  name: "ICARUS: Dedicated Server",
  tagline: "Survive the alien frontier with your crew",
  description:
    "Host a persistent ICARUS dedicated server with prospect (world) management, admin controls and Steam-based join. Runs the official Windows server under Wine via SteamCMD, fully managed by MGG — no Windows box required.",
  author: "MGG",
  icon: "🪐",
  color: "#E0552B",
  category: "survival",
  dockerImages: {
    "SteamCMD + Wine (mornedhels)": "mornedhels/icarus-server:latest",
    "SteamCMD + Wine (jammsen)": "jammsen/docker-icarus-dedicated-server:latest",
  },
  defaultImage: "mornedhels/icarus-server:latest",
  startupCommand: "",
  // Icarus has no RCON; the wrapper traps SIGTERM to save & shut down cleanly.
  stopCommand: "^SIGTERM",
  stopSignal: "SIGTERM",
  // The mornedhels image never prints "Started Steam Server"; the reliable
  // "ready for players" signal is LogNet binding the SteamNetDriver to the game
  // port (printed once, after the world/engine finish loading). Match that (plus
  // the specific supervisord line for the game process) so the panel flips the
  // server to "running" instead of being stuck on "starting" forever.
  startupDoneRegex: "bound to port|icarus-server entered RUNNING state|Started Steam Server|Server is ready|Game state updated",
  docsUrl: "https://github.com/jammsen/docker-icarus-dedicated-server",
  dataPath: "/home/icarus",
  resources: { memoryMb: 8192, cpuPercent: 300, diskMb: 20480 },
  features: ["steamcmd", "wine", "query", "world-upload"],
  // ⚠️ The mornedhels image reads SERVER_PORT (-PORT) and SERVER_QUERYPORT
  // (-QueryPort) — NOT GAME_PORT/QUERY_PORT. The panel already injects
  // SERVER_PORT = primary port, but the query port MUST be exported as
  // SERVER_QUERYPORT or the server falls back to the default 27015 (unpublished)
  // and never answers A2S → it stays invisible in the in-game browser.
  ports: [
    { name: "Game", protocol: "udp", default: 17777, envVar: "SERVER_PORT", primary: true },
    { name: "Query", protocol: "udp", default: 27015, envVar: "SERVER_QUERYPORT", offsetFromPrimary: 9238 },
  ],
  variables: [
    {
      key: "SERVER_NAME",
      name: "Server name",
      description: "Name shown in the in-game server browser.",
      default: "MGG ICARUS Server",
      userViewable: true,
      userEditable: true,
      type: "string",
      rules: "required|string",
      group: "General",
    },
    {
      key: "SERVER_MAX_PLAYERS",
      name: "Max players",
      description: "Maximum players (Icarus supports up to 8 by default).",
      default: "8",
      userViewable: true,
      userEditable: true,
      type: "number",
      rules: "integer|between:1,64",
      group: "General",
    },
    {
      key: "SERVER_PASSWORD",
      name: "Join password",
      description: "Password players must enter to join. Leave blank for an open server.",
      default: "",
      userViewable: true,
      userEditable: true,
      type: "string",
      rules: "string",
      group: "Access",
    },
    {
      key: "SERVER_ADMIN_PASSWORD",
      name: "Admin password",
      description: "Grants in-game admin powers. Auto-generated by default.",
      default: "{{RANDOM}}",
      userViewable: true,
      userEditable: true,
      type: "string",
      rules: "required|string",
      group: "Access",
    },
    {
      key: "ICARUS_ADMIN_STEAMIDS",
      name: "Admins (SteamID64)",
      description:
        "Liste de SteamID64 (séparés par des virgules) considérés comme admins. Ces joueurs apparaissent en doré dans « Joueurs connectés ». Icarus ne loguant pas qui est admin, c'est cette liste qui fait foi.",
      default: "",
      userViewable: true,
      userEditable: true,
      type: "string",
      rules: "string",
      group: "Access",
    },
    {
      key: "SERVER_RESUME_PROSPECT",
      name: "Reprendre le prospect au démarrage",
      description:
        "Recharge automatiquement le dernier prospect (monde/mission) à chaque démarrage du serveur. Sans ça, un admin doit relancer le monde à la main après chaque redémarrage. Recommandé : activé.",
      default: "true",
      userViewable: true,
      userEditable: true,
      type: "boolean",
      rules: "boolean",
      group: "Prospects",
    },
    {
      key: "SERVER_ALLOW_NON_ADMINS_LAUNCH",
      name: "Joueurs peuvent lancer des prospects",
      description: "Autorise les non-admins à démarrer de nouveaux prospects (missions / mondes ouverts).",
      default: "true",
      userViewable: true,
      userEditable: true,
      type: "boolean",
      rules: "boolean",
      group: "Prospects",
    },
    {
      key: "SERVER_ALLOW_NON_ADMINS_DELETE",
      name: "Joueurs peuvent supprimer des prospects",
      description: "Autorise les non-admins à supprimer des prospects. Déconseillé (risque de perte du monde).",
      default: "false",
      userViewable: true,
      userEditable: true,
      type: "boolean",
      rules: "boolean",
      group: "Prospects",
    },
    {
      key: "SERVER_SHUTDOWN_IF_NOT_JOINED",
      name: "Idle shutdown (no join), s",
      description: "Shut the prospect down if nobody joins for this many seconds. 0 disables.",
      default: "0",
      userViewable: true,
      userEditable: true,
      type: "number",
      rules: "integer",
      group: "Gameplay",
    },
    {
      key: "SERVER_SHUTDOWN_IF_EMPTY",
      name: "Idle shutdown (empty), s",
      description: "Shut the prospect down once empty for this many seconds. 0 disables.",
      default: "0",
      userViewable: true,
      userEditable: true,
      type: "number",
      rules: "integer",
      group: "Gameplay",
    },
    {
      key: "STEAM_APP_VALIDATE",
      name: "Validate on update",
      description: "Run SteamCMD validation when updating (slower but safer).",
      default: "true",
      userViewable: true,
      userEditable: true,
      type: "boolean",
      rules: "boolean",
      group: "System",
    },
    {
      key: "GAME_BRANCH",
      name: "Branche Steam",
      description: "Branche de mise à jour Steam : 'public' (stable) ou 'experimental' (bêta).",
      default: "public",
      userViewable: true,
      userEditable: true,
      type: "string",
      rules: "string",
      group: "Maintenance",
    },
    {
      key: "UPDATE_CRON",
      name: "Mise à jour auto (cron)",
      description:
        "Planifie les MAJ automatiques du serveur (syntaxe cron, ex. '0 5 * * *' = chaque jour à 5h). Vide = aucune MAJ planifiée.",
      default: "",
      userViewable: true,
      userEditable: true,
      type: "string",
      rules: "string",
      group: "Maintenance",
    },
    {
      key: "UPDATE_SKIP",
      name: "Ne pas vérifier les MAJ au démarrage",
      description: "Saute la vérification SteamCMD au démarrage (démarrage plus rapide, mais le serveur peut être en retard de version).",
      default: "false",
      userViewable: true,
      userEditable: true,
      type: "boolean",
      rules: "boolean",
      group: "Maintenance",
    },
    {
      key: "CLEANUP_CRON",
      name: "Nettoyage auto des sauvegardes (cron)",
      description:
        "Planifie le nettoyage automatique des anciennes sauvegardes de prospects (syntaxe cron, ex. '0 4 * * *'). Vide = désactivé.",
      default: "",
      userViewable: true,
      userEditable: true,
      type: "string",
      rules: "string",
      group: "Maintenance",
    },
    {
      key: "CLEANUP_DAYS",
      name: "Nettoyage : âge max (jours)",
      description: "Lors du nettoyage, archive les sauvegardes de prospects plus vieilles que ce nombre de jours.",
      default: "7",
      userViewable: true,
      userEditable: true,
      type: "number",
      rules: "integer|between:1,365",
      group: "Maintenance",
    },
  ],
  install: {
    // The image performs the SteamCMD download/validate of app 2089300 on first boot.
    image: "jammsen/docker-icarus-dedicated-server:latest",
    entrypoint: "bash",
    script:
      '#!/bin/bash\necho "[MGG] ICARUS will download via SteamCMD (AppID 2089300) and prepare Wine on first boot."\necho "[MGG] This first boot can take several minutes depending on bandwidth."\n',
  },
  configFiles: [
    {
      path: "ServerSettings.ini",
      parser: "ini",
      fields: {
        ServerName: { label: "Server name", default: "MGG ICARUS Server" },
        MaxPlayers: { label: "Max players", default: "8", type: "number" },
        JoinPassword: { label: "Join password", default: "" },
      },
    },
  ],
};
