import type { GameTemplate } from "./template.js";

/**
 * Minecraft: Java Edition.
 * Powered by the battle-tested `itzg/minecraft-server` image which self-provisions
 * the chosen flavour/version on first boot, exposes RCON, manages EULA, plugins,
 * mods and modpacks — all driven by environment variables.
 */
export const minecraftJava: GameTemplate = {
  id: "minecraft-java",
  game: "minecraft",
  name: "Minecraft: Java Edition",
  tagline: "Vanilla, Paper, Fabric, Forge, NeoForge & more",
  description:
    "The full Java Edition experience. Pick any flavour (Paper, Purpur, Fabric, Forge, NeoForge, Quilt, Vanilla) and any version, then install plugins and mods in one click. RCON console, fast Aikar JVM flags and auto world management included.",
  author: "MGG",
  icon: "🟩",
  color: "#5BA744",
  category: "minecraft",
  dockerImages: {
    // The default. Ships the newest JDK so it always matches VERSION=LATEST
    // (recent Minecraft, e.g. 26.1+, requires Java 25 — an older java21 image
    // boots-fails with "requires running the server with Java 25 or above").
    "Latest (newest MC · Java 25)": "itzg/minecraft-server:latest",
    "Java 25 (MC 26.1+)": "itzg/minecraft-server:java25",
    "Java 21 (1.20.5–1.21.x)": "itzg/minecraft-server:java21",
    "Java 17 (1.17–1.20.4)": "itzg/minecraft-server:java17",
    "Java 8 (1.7–1.16)": "itzg/minecraft-server:java8-multiarch",
  },
  defaultImage: "itzg/minecraft-server:latest",
  // The itzg image has its own smart entrypoint; we drive it purely with env.
  startupCommand: "",
  stopCommand: "stop",
  stopSignal: "SIGTERM",
  startupDoneRegex: "\\)! For help, type",
  rcon: { envPort: "RCON_PORT", envPassword: "RCON_PASSWORD", defaultPort: 25575 },
  docsUrl: "https://docker-minecraft-server.readthedocs.io/",
  resources: { memoryMb: 4096, cpuPercent: 200, diskMb: 10240 },
  features: [
    "rcon",
    "query",
    "eula",
    "plugins",
    "mods",
    "modpacks",
    "console-input",
    "world-upload",
    "auto-pause",
  ],
  ports: [
    { name: "Game", protocol: "both", default: 25565, envVar: "SERVER_PORT", primary: true },
    { name: "RCON", protocol: "tcp", default: 25575, envVar: "RCON_PORT", offsetFromPrimary: 10 },
  ],
  variables: [
    {
      key: "EULA",
      name: "Accept the Minecraft EULA",
      description: "You must accept the Mojang EULA (https://aka.ms/MinecraftEULA) to run a server.",
      default: "TRUE",
      userViewable: true,
      userEditable: true,
      type: "boolean",
      rules: "required|boolean",
      group: "General",
    },
    {
      key: "TYPE",
      name: "Server software",
      description: "The server flavour. Paper is recommended for plugins; Fabric/Forge/NeoForge for mods.",
      default: "PAPER",
      userViewable: true,
      userEditable: true,
      type: "enum",
      rules: "required|string",
      group: "General",
      options: [
        { value: "PAPER", label: "Paper (plugins, fast)" },
        { value: "PURPUR", label: "Purpur (Paper fork, more options)" },
        { value: "FABRIC", label: "Fabric (mods)" },
        { value: "FORGE", label: "Forge (mods)" },
        { value: "NEOFORGE", label: "NeoForge (mods)" },
        { value: "QUILT", label: "Quilt (mods)" },
        { value: "SPIGOT", label: "Spigot (plugins)" },
        { value: "VANILLA", label: "Vanilla (official)" },
      ],
    },
    {
      key: "VERSION",
      name: "Minecraft version",
      description: 'Game version, e.g. "1.21.4", or LATEST / SNAPSHOT.',
      default: "LATEST",
      userViewable: true,
      userEditable: true,
      type: "string",
      rules: "required|string",
      group: "General",
    },
    {
      key: "MOTD",
      name: "Message of the day",
      description: "Shown in the server list. Supports colour codes (§).",
      default: "§bPowered by §lMGG",
      userViewable: true,
      userEditable: true,
      type: "string",
      rules: "string",
      group: "World",
    },
    {
      key: "DIFFICULTY",
      name: "Difficulty",
      description: "peaceful, easy, normal or hard.",
      default: "normal",
      userViewable: true,
      userEditable: true,
      type: "enum",
      rules: "string",
      group: "World",
      options: ["peaceful", "easy", "normal", "hard"].map((v) => ({ value: v, label: v })),
    },
    {
      key: "MODE",
      name: "Game mode",
      description: "survival, creative, adventure or spectator.",
      default: "survival",
      userViewable: true,
      userEditable: true,
      type: "enum",
      rules: "string",
      group: "World",
      options: ["survival", "creative", "adventure", "spectator"].map((v) => ({ value: v, label: v })),
    },
    {
      key: "MAX_PLAYERS",
      name: "Max players",
      description: "Maximum simultaneous players.",
      default: "20",
      userViewable: true,
      userEditable: true,
      type: "number",
      rules: "integer|between:1,1000",
      group: "World",
    },
    {
      key: "ONLINE_MODE",
      name: "Online mode (premium auth)",
      description:
        "TRUE verifies players against Mojang/Microsoft. Set FALSE only behind a proxy or for a custom-auth (cracked) network — required if your custom launcher uses a custom auth server.",
      default: "TRUE",
      userViewable: true,
      userEditable: true,
      type: "boolean",
      rules: "required|boolean",
      group: "Network",
    },
    {
      key: "USE_AIKAR_FLAGS",
      name: "Aikar JVM flags",
      description: "Apply Aikar's tuned garbage-collection flags for smoother performance.",
      default: "true",
      userViewable: true,
      userEditable: true,
      type: "boolean",
      rules: "boolean",
      group: "Performance",
    },
    {
      key: "MODRINTH_MODPACK",
      name: "Modrinth modpack",
      description: "Optional: a Modrinth modpack slug or URL to auto-install (Fabric/Forge/Quilt).",
      default: "",
      userViewable: true,
      userEditable: true,
      type: "string",
      rules: "string",
      group: "Content",
    },
    {
      key: "MODRINTH_PROJECTS",
      name: "Modrinth plugins/mods",
      description: "Comma-separated Modrinth slugs to auto-install (e.g. fabric-api,lithium).",
      default: "",
      userViewable: true,
      userEditable: true,
      type: "string",
      rules: "string",
      group: "Content",
    },
    {
      key: "SPIGET_RESOURCES",
      name: "SpigotMC plugins",
      description: "Comma-separated SpigotMC resource IDs to auto-install.",
      default: "",
      userViewable: true,
      userEditable: true,
      type: "string",
      rules: "string",
      group: "Content",
    },
    {
      key: "RCON_PASSWORD",
      name: "RCON password",
      description: "Password for the remote console. Auto-generated; keep it secret.",
      default: "{{RANDOM}}",
      userViewable: false,
      userEditable: false,
      type: "string",
      rules: "required|string",
      group: "System",
    },
    {
      key: "MEMORY",
      name: "JVM heap override",
      description: "Leave blank to let MGG size the heap from your plan's RAM.",
      default: "",
      userViewable: false,
      userEditable: false,
      type: "string",
      rules: "string",
      group: "System",
    },
  ],
  install: {
    image: "itzg/minecraft-server:latest",
    entrypoint: "bash",
    script:
      '#!/bin/bash\necho "[MGG] Minecraft self-provisions on first boot (flavour: $TYPE, version: $VERSION)."\necho "[MGG] Install step complete."\n',
  },
  configFiles: [
    {
      path: "server.properties",
      parser: "properties",
      fields: {
        "max-players": { label: "Max players", default: "20", type: "number" },
        "view-distance": { label: "View distance", default: "10", type: "number" },
        "simulation-distance": { label: "Simulation distance", default: "10", type: "number" },
        "spawn-protection": { label: "Spawn protection", default: "16", type: "number" },
        pvp: { label: "PvP", default: "true", type: "boolean" },
        "allow-flight": { label: "Allow flight", default: "false", type: "boolean" },
        "white-list": { label: "Whitelist", default: "false", type: "boolean" },
      },
    },
  ],
};

/** Minecraft: Bedrock Edition (mobile / console / Windows 10). */
export const minecraftBedrock: GameTemplate = {
  id: "minecraft-bedrock",
  game: "minecraft",
  name: "Minecraft: Bedrock Edition",
  tagline: "Mobile, console & Windows cross-play",
  description:
    "Host a Bedrock dedicated server for cross-platform play across mobile, console and Windows. Add-ons supported.",
  author: "MGG",
  icon: "🧱",
  color: "#7AB648",
  category: "minecraft",
  dockerImages: { Latest: "itzg/minecraft-bedrock-server:latest" },
  defaultImage: "itzg/minecraft-bedrock-server:latest",
  startupCommand: "",
  stopCommand: "stop",
  stopSignal: "SIGTERM",
  startupDoneRegex: "Server started",
  resources: { memoryMb: 2048, cpuPercent: 150, diskMb: 6144 },
  features: ["eula", "console-input", "world-upload"],
  ports: [{ name: "Game", protocol: "udp", default: 19132, envVar: "SERVER_PORT", primary: true }],
  variables: [
    { key: "EULA", name: "Accept the Minecraft EULA", description: "Required.", default: "TRUE", userViewable: true, userEditable: true, type: "boolean", rules: "required|boolean", group: "General" },
    { key: "VERSION", name: "Version", description: "LATEST or a specific Bedrock version.", default: "LATEST", userViewable: true, userEditable: true, type: "string", rules: "required|string", group: "General" },
    { key: "GAMEMODE", name: "Game mode", description: "survival / creative / adventure.", default: "survival", userViewable: true, userEditable: true, type: "enum", rules: "string", group: "World", options: ["survival", "creative", "adventure"].map((v) => ({ value: v, label: v })) },
    { key: "DIFFICULTY", name: "Difficulty", description: "peaceful / easy / normal / hard.", default: "normal", userViewable: true, userEditable: true, type: "enum", rules: "string", group: "World", options: ["peaceful", "easy", "normal", "hard"].map((v) => ({ value: v, label: v })) },
    { key: "SERVER_NAME", name: "Server name", description: "Shown in the friends list.", default: "MGG Bedrock", userViewable: true, userEditable: true, type: "string", rules: "string", group: "World" },
    { key: "MAX_PLAYERS", name: "Max players", description: "Max simultaneous players.", default: "10", userViewable: true, userEditable: true, type: "number", rules: "integer|between:1,100", group: "World" },
  ],
  install: { image: "itzg/minecraft-bedrock-server:latest", entrypoint: "bash", script: '#!/bin/bash\necho "[MGG] Bedrock self-provisions on first boot."\n' },
};
